version: '3.1'
services:
  jenkins:
    image: ${IMAGE}:${TAG}
    build:
      context: .
      args:
        DOCKER_GID: ${DOCKER_GID}
    container_name: jenkins
    environment:
      TZ: "Asia/Seoul"
      JAVA_OPTS: "-Dhudson.model.DownloadService.noSignatureCheck=true"
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - ./data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock